language: node_js
node_js: 
    - "0.10"
addons:
    sauce_connect: true
env: 
  global: 
      - secure: AmG4KmgELDGWeYjQ2BNGRG/yuhwDdVPdLekr/paySTL320CxcFY7aPJPht9iSytmq95N5fbF/6I7aqEZg5SoVuaPi81a8xvj/SCeV0dE0nzHV/EwadgdkOSxZ8+ctbN1hVOrcBLsPMOrVPaWP9zBCRAC5Q1TOE/r+N0BrQMhahA=
      - secure: PEgAZikBNY1sI6j8NZ+wFQOJQa5xNY1XOryGNgfytN9rbY7WvYYiS4aXMSKfjUjtDjRcFIzskYfOLaYPPlaa928Kzo9zdZx8A55Aa/UcKdx4pze9IuaCtzUMtwuuZM8FTUiO+tmOUQJ46PN1X36Yh4CFF7BlZFynGerUwkoo3h4=
install:
    - npm -g install mocha grunt-cli serve
    - echo -e "\x1b\x5b35;1m*** Checking out Enyo\x1b\x5b0m"
    - git clone --depth 1 https://github.com/enyojs/enyo.git enyo
    - mkdir lib
    - echo -e "\x1b\x5b35;1m*** Checking out Moonstone\x1b\x5b0m"
    - git clone --depth 1 https://github.com/enyojs/moonstone.git lib/moonstone
    - echo -e "\x1b\x5b35;1m*** Checking out Layout\x1b\x5b0m"
    - git clone --depth 1 https://github.com/enyojs/layout.git lib/layout
    - echo -e "\x1b\x5b35;1m*** Checking out iLib\x1b\x5b0m"
    - git clone --depth 1 https://github.com/enyojs/enyo-ilib.git lib/enyo-ilib
    - echo -e "\x1b\x5b35;1m*** Checking out Spotlight\x1b\x5b0m"
    - git clone --depth 1 https://github.com/enyojs/spotlight.git lib/spotlight
    - echo -e "\x1b\x5b35;1m*** Installing npm modules\x1b\x5b0m"
    - npm install
before_script:
    - serve -L &
script:
    - echo -e "\x1b\x5b35;1m*** Starting tests...\x1b\x5b0m"
    - grunt
    - echo -e "\x1b\x5b35;1m*** Tests complete\x1b\x5b0m"

